export const data = [
    {
        id:1,
        img:'assets/images/client/1.jpg',      
    },
    {
        id:2,
        img:'assets/images/client/2.jpg',      
    },
    {
        id:3,
        img:'assets/images/client/3.jpg',   
    },
    {
        id:4,
        img:'assets/images/client/4.jpg',   
    },
    {
        id:5,
        img:'assets/images/client/5.jpg',   
    },
    {
        id:6,
        img:'assets/images/client/6.jpg',   
    },
    {
        id:7,
        img:'assets/images/client/7.jpg',   
    },
    {
        id:8,
        img:'assets/images/client/8.jpg',   
    },
    {
        id:9,
        img:'assets/images/client/9.jpg',   
    },
    {
        id:10,
        img:'assets/images/client/10.jpg',   
    },
]